spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: collector
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
batch-execution:
  file-name: panini-manga-titles
  folder: panini-manga-mx