spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: collector
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
batch-execution:
  datasource:
    h2:
      jdbc-url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
  file-name: panini-manga-titles
  folder: panini-manga-mx